version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=cyberskwal_javaprojectaws -Dsonar.organization=cyberskwal -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=0f35ad04acf9fe05c246db7643b8f6d777eba132 
